matrix:
  include:
  - os: osx
    language: node_js
    node_js:
    - lts/*
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    language: node_js
    node_js:
    - lts/*
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-multilib
        - gcc-8
        - g++-8
        - g++-multilib
        - icnsutils
        - graphicsmagick
        - xz-utils
        - xorriso
        - rpm
  - os: windows
    language: node_js
    node_js:
    - lts/*
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN_GPG=no
before_install:
- yarn install --network-timeout 1000000
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-8"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC="gcc-8"; fi

install:
- yarn --ignore-engines
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    /sbin/start-stop-daemon \
    --start \
    --quiet \
    --pidfile /tmp/custom_xvfb_99.pid \
    --make-pidfile \
    --background \
    --exec /usr/bin/Xvfb \
    -- :99 -ac -screen 0 1280x1024x16
  else
    :
  fi
script:
- yarn package
before_deploy:
  - rm -rf ./release/*.blockmap
  - rm -rf ./release/*.zip
dist: xenial

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "release/ninja-pro-wallet*"
    skip_cleanup: true
    on:
      tags: true
